package utils

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
)

type Generator interface {
	Generate() error
	Tests() error
}

// FixedSizeTypes is a map of Go types that have a fixed marshalled size.
var FixedSizeTypes = map[string]bool{
	"bool": true, "byte": true, "rune": true, "int8": true, "uint8": true,
	"int16": true, "uint16": true, "int32": true, "uint32": true,
	"int64": true, "uint64": true, "float32": true, "float64": true,
	"time.Time": true,
}

// GenContext holds the shared state of the generation process (AST info).
type GenContext struct {
	InputFile, PkgName, BaseName, OutputDir   string
	TypeSpecs map[string]*ast.TypeSpec
	Types []*ast.TypeSpec
	buf bytes.Buffer
}

// NewContext creates a new shared context.
func NewContext(inputFile string) (ctx *GenContext) {
	ctx =  &GenContext{
		InputFile: inputFile,
		TypeSpecs: make(map[string]*ast.TypeSpec),
		BaseName: strings.TrimSuffix(filepath.Base(inputFile), filepath.Ext(inputFile)),
		OutputDir: filepath.Dir(inputFile),
	}

	return
}

func (ctx *GenContext) Type2TypeSpecs() bool {
	if len(ctx.Types) == 0 {
		log.Printf("no structs or classes found in %s", ctx.InputFile)
		return false
	}

	for _, t := range ctx.Types {
		ctx.TypeSpecs[t.Name.Name] = t
	}

	return true
}

// ExprToString converts an AST expression to its string representation.
func (c *GenContext) ExprToString(expr ast.Expr) string {
	var b bytes.Buffer
	if err := format.Node(&b, token.NewFileSet(), expr); err != nil {
		log.Printf("failed to convert expr to string: %v", err)
		return ""
	}
	return b.String()
}

// ShouldIgnoreField checks if the field has a //benc:ignore comment.
func (c *GenContext) ShouldIgnoreField(field *ast.Field) bool {
	checkGroup := func(cg *ast.CommentGroup) bool {
		if cg == nil {
			return false
		}
		for _, cm := range cg.List {
			if strings.Contains(cm.Text, "//benc:ignore") {
				return true
			}
		}
		return false
	}
	return checkGroup(field.Doc) || checkGroup(field.Comment)
}

// IsUnsupportedType recursively checks if a type expression contains an ignored type.
func (c *GenContext) IsUnsupportedType(expr ast.Expr) bool {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "any", "complex64", "complex128", "uintptr", "chan", "func", "error":
			return true
		default:
			if ts, ok := c.TypeSpecs[t.Name]; ok {
				return c.IsUnsupportedType(ts.Type)
			}
			return false
		}
	case *ast.FuncType, *ast.ChanType:
		return true
	case *ast.InterfaceType:
		return true
	case *ast.ArrayType:
		return c.IsUnsupportedType(t.Elt)
	case *ast.MapType:
		return c.IsUnsupportedType(t.Key) || c.IsUnsupportedType(t.Value)
	case *ast.StarExpr:
		return c.IsUnsupportedType(t.X)
	case *ast.SelectorExpr:
		sel := c.ExprToString(t)
		if sel == "sync.Mutex" || sel == "sync.RWMutex" || sel == "unsafe.Pointer" {
			return true
		}
		return false
	case *ast.StructType:
		if t.Fields == nil {
			return true
		}
		return len(t.Fields.List) == 0
	default:
		return false
	}
}

// GetSupportedFields filters fields of a struct based on ignore tags and unsupported types.
func (c *GenContext) GetSupportedFields(ts *ast.TypeSpec) []*ast.Field {
	var supportedFields []*ast.Field
	name := ts.Name.Name
	for _, field := range ts.Type.(*ast.StructType).Fields.List {
		if c.ShouldIgnoreField(field) {
			continue
		}
		if c.IsUnsupportedType(field.Type) {
			for _, fName := range field.Names {
				log.Printf("INFO: Skipping unsupported field %s.%s", name, fName.Name)
			}
			continue
		}
		supportedFields = append(supportedFields, field)
	}
	return supportedFields
}

func (ctx *GenContext) WriteFile(content *bytes.Buffer, prefix, lang string) error {
	path := filepath.Join(ctx.OutputDir, fmt.Sprintf("%s_"+prefix+"."+lang, ctx.BaseName))
	if err := os.WriteFile(path, content.Bytes(), 0644); err != nil {
		log.Fatalf("failed to write file %s: %v", path, err)
		return err
	}

	content.Reset()

	log.Printf("Successfully generated %s", path)

	return nil
}

func (ctx *GenContext) ParseGO() {
	log.Printf("Parsing GO input: %s", ctx.InputFile)

	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, ctx.InputFile, nil, parser.ParseComments)
	if err != nil {
		log.Fatalf("failed to parse input file %s: %v", ctx.InputFile, err)
	}

	ctx.PkgName = node.Name.Name

	ast.Inspect(node, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok {
			return true
		}
		switch ts.Type.(type) {
		case *ast.StructType, *ast.MapType:
			ctx.Types = append(ctx.Types, ts)
		}
		return false
	})
}

func (ctx *GenContext) Tests() (err error) {
	ctx.printf("// Code generated by benc generator; DO NOT EDIT.\n\n")
	ctx.printf("package %s\n\n", ctx.PkgName)
	ctx.printf("import (\n")
	ctx.printf("\t\"math/rand\"\n")
	ctx.printf("\t\"testing\"\n")
	ctx.printf("\t\"time\"\n\n")
	ctx.printf("\t \"github.com/banditmoscow1337/utils\"\n")
	ctx.printf(")\n\n")

	for _, ts := range ctx.Types {
		ctx.generateGoTestGenerator(ts)
		//ctx.generateGoTestComparer(ts)
	}

	var topLevelStruct *ast.TypeSpec
	for _, ts := range ctx.Types {
		if _, ok := ts.Type.(*ast.StructType); ok {
			if topLevelStruct == nil {
				topLevelStruct = ts
			}
		}
	}

	// if topLevelStruct != nil {
	// 	ctx.generateGoTestMain(topLevelStruct)
	// }

	return ctx.formatGo("benc_test")
}

func (ctx *GenContext) formatGo(prefix string) (err error) {
	src, err := format.Source(ctx.buf.Bytes())
	if err != nil {
		log.Printf("---BEGIN FAILED SOURCE---\n%s\n---END FAILED SOURCE---", ctx.buf.String())
		return fmt.Errorf("failed to format generated code: %w", err)
	}

	ctx.buf.Reset()

	if _, err = ctx.buf.Write(src); err!=nil {
		return 
	}

	ctx.WriteFile(&ctx.buf, prefix, "go")

	ctx.buf.Reset()
	return nil
}

func (ctx *GenContext) generateGoTestGenerator(ts *ast.TypeSpec) {
	name := ts.Name.Name
	ctx.printf("func Generate%s(r *rand.Rand, depth int) %s {\n", name, name)
	ctx.printf("\tif depth <= 0 { return *new(%s) }\n", name)
	switch t := ts.Type.(type) {
	case *ast.StructType:
		ctx.printf("\treturn %s{\n", name)
		for _, field := range t.Fields.List {
			if ctx.ShouldIgnoreField(field) || ctx.IsUnsupportedType(field.Type) {
				continue
			}
			for _, fName := range field.Names {
				gen := ctx.getTypeInfo(field.Type).TestGenerator
				if strings.HasPrefix(gen, "func") {
					gen = fmt.Sprintf("(%s)(r, depth-1)", gen)
				} else {
					gen = fmt.Sprintf("%s(r, depth-1)", gen)
				}
				ctx.printf("\t\t%s: %s,\n", fName.Name, gen)
			}
		}
		ctx.printf("\t}\n")
	case *ast.MapType, *ast.ArrayType:
		if ctx.IsUnsupportedType(ts.Type) {
			ctx.printf("\treturn nil\n")
		} else {
			gen := ctx.getTypeInfo(ts.Type).TestGenerator
			ctx.printf("\treturn (%s)(r, depth-1)\n", gen)
		}
	default:
		gen := ctx.getTypeInfo(ts.Type).TestGenerator
		ctx.printf("\treturn %s(r, depth-1)\n", gen)
	}
	ctx.printf("}\n\n")
}

func (ctx *GenContext) printf(format string, args ...interface{}) {
	_, _ = fmt.Fprintf(&ctx.buf, format, args...)
}
type typeGenInfo struct {
	TypeName      string
	TestGenerator string
	IsFixedSize   bool
}

func (ctx *GenContext) getTypeInfo(expr ast.Expr) typeGenInfo {
	typeName := ctx.ExprToString(expr)

	switch t := expr.(type) {
	case *ast.Ident:
		if _, ok := ctx.TypeSpecs[t.Name]; ok {
			return typeGenInfo{
				TypeName:      t.Name,
				TestGenerator: fmt.Sprintf("Generate%s", t.Name),
			}
		}
		title := strings.Title(t.Name)
		if t.Name == "byte" || t.Name == "uint8" {
			title = "Byte"
			typeName = "byte"
		}
		if t.Name == "rune" {
			title = "Int32"
			typeName = "rune"
		}
		if t.Name == "uintptr" {
			title = "Uintptr"
		}
		return typeGenInfo{
			TypeName:      typeName,
			TestGenerator: "utils.Generate" + title,
			IsFixedSize:   FixedSizeTypes[t.Name],
		}

	case *ast.StarExpr:
		eltInfo := ctx.getTypeInfo(t.X)
		return typeGenInfo{
			TypeName:      "*" + eltInfo.TypeName,
			TestGenerator: fmt.Sprintf("func(r *rand.Rand, d int) *%s { return utils.GeneratePointer(r, d, %s) }", eltInfo.TypeName, eltInfo.TestGenerator),
		}

	case *ast.SelectorExpr:
		sel := ctx.ExprToString(t)
		if sel == "time.Time" {
			return typeGenInfo{
				TypeName:      "time.Time",
				TestGenerator: "utils.GenerateTime",
				IsFixedSize:   true,
			}
		}
		return typeGenInfo{
			TypeName:      sel,
			TestGenerator: fmt.Sprintf("func(r *rand.Rand, d int) %s { return *new(%s) }", sel, sel),
		}

	case *ast.ArrayType:
		eltInfo := ctx.getTypeInfo(t.Elt)
		
		if t.Len != nil {
			// Fixed Array logic
			lenStr := ctx.ExprToString(t.Len)
			
			// Generator construction
			genCall := eltInfo.TestGenerator
			if strings.HasPrefix(genCall, "func") {
				genCall = fmt.Sprintf("(%s)(r, d)", genCall)
			} else {
				genCall = fmt.Sprintf("%s(r, d)", genCall)
			}
			
			testGen := fmt.Sprintf("func(r *rand.Rand, d int) %s { var v %s; for i := 0; i < %s; i++ { v[i] = %s }; return v }", typeName, typeName, lenStr, genCall)

			return typeGenInfo{
				TypeName: typeName,
				TestGenerator: testGen,
				IsFixedSize: eltInfo.IsFixedSize,
			}
		}

		return typeGenInfo{
			TypeName:      typeName,
			TestGenerator: fmt.Sprintf("func(r *rand.Rand, d int) %s { return utils.GenerateSlice(r, d, %s) }", typeName, eltInfo.TestGenerator),
		}

	case *ast.MapType:
		keyInfo := ctx.getTypeInfo(t.Key)
		valInfo := ctx.getTypeInfo(t.Value)
		
		// Check if Key is a pointer

		return typeGenInfo{
			TypeName:      typeName,
			TestGenerator: fmt.Sprintf("func(r *rand.Rand, d int) %s { return utils.GenerateMap(r, d, %s, %s) }", typeName, keyInfo.TestGenerator, valInfo.TestGenerator),
			
		}
	}
	return typeGenInfo{TypeName: typeName}
}